variables:
  projectBridge:  './Plotly.Bridge/Plotly.Bridge.csproj'
  projectH5:  './Plotly.H5/Plotly.H5.csproj'
  projectSharp:  './Plotly.Sharp/Plotly.Sharp.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: NuGetToolInstaller@1

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 3.1.401
    installationPath: $(Agent.ToolsDirectory)/dotnet
    
- task: CmdLine@2
  inputs:
    script: 'dotnet tool update --global h5-compiler'

- task: DotNetCoreCLI@2
  displayName: 'restore nuget'
  inputs:
    command: 'restore'
    projects: '$(projectH5)'

- task: DotNetCoreCLI@2
  displayName: 'build'
  inputs:
    command: 'build'
    projects: '$(projectH5)'
    arguments: '-c $(buildConfiguration) /p:Version=0.0.$(build.buildId)  /p:AllowUnsafeBlocks=True /p:LangVersion=latest'

- task: DotNetCoreCLI@2
  displayName: 'pack nuget'
  inputs:
    command: 'pack'
    packagesToPack: '$(projectH5)'
    configuration: '$(buildConfiguration)'
    versioningScheme: 'off'
    buildProperties: 'Version="0.0.$(build.buildId)";AllowUnsafeBlocks="True";LangVersion="latest"'

- task: DotNetCoreCLI@2
  displayName: 'restore projectBridge'
  inputs:
    command: 'restore'
    projects: '$(projectBridge)'


- task: DotNetCoreCLI@2
  displayName: 'restore projectSharp'
  inputs:
    command: 'restore'
    projects: '$(projectSharp)'

    
- task: VSBuild@1
  displayName: 'build projectBridge'
  inputs:
    solution: '$(projectBridge)'
    msbuildArgs: '/t:pack /p:Version=0.0.$(build.buildId)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSBuild@1
  displayName: 'build projectSharp'
  inputs:
    solution: '$(projectSharp)'
    msbuildArgs: '/t:pack /p:Version=0.0.$(build.buildId)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CmdLine@2
  inputs:
    script: 'dir $(Build.SourcesDirectory)\*.nupkg /S'

- task: NuGetCommand@2
  displayName: 'push Plotly.Bridge to nuget'
  inputs:
    command: 'push'
    packagesToPush: '**/Plotly.Bridge.0.0.$(build.buildId).nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget-curiosity'

- task: NuGetCommand@2
  displayName: 'push Plotly.H5 to nuget'
  inputs:
    command: 'push'
    packagesToPush: '**/Plotly.H5.0.0.$(build.buildId).nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget-curiosity'


- task: NuGetCommand@2
  displayName: 'push Plotly.Sharp to nuget'
  inputs:
    command: 'push'
    packagesToPush: '**/Plotly.Sharp.0.0.$(build.buildId).nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget-curiosity-org'

