variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

steps:
- task: NuGetToolInstaller@0

- task: DotNetCoreInstaller@0
  displayName: 'Install .net core 3.0'
  inputs:
    version: '3.0.100'

- task: VSBuild@1
  displayName: 'build solution'
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/t:pack /p:Version=0.0.$(build.buildId)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    restoreNugetPackages: true

- task: CmdLine@2
  inputs:
    script: 'dir $(Build.SourcesDirectory)\*.nupkg /S'

- task: NuGetCommand@2
  displayName: 'push PlotlyBridge to nuget'
  inputs:
    command: 'push'
    packagesToPush: '**/PlotlyBridge.0.0.$(build.buildId).nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget-curiosity'