variables:
  project:  './Plotly.Bridge/Plotly.Bridge.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

steps:
- task: NuGetToolInstaller@0

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(project)'
    displayName: 'restore nuget'


- task: VSBuild@1
  displayName: 'build project'
  inputs:
    solution: '$(project)'
    msbuildArgs: '/t:pack /p:Version=0.0.$(build.buildId)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CmdLine@2
  inputs:
    script: 'dir $(Build.SourcesDirectory)\*.nupkg /S'

- task: NuGetCommand@2
  displayName: 'push Plotly.Bridge to nuget'
  inputs:
    command: 'push'
    packagesToPush: '**/Plotly.Bridge.0.0.$(build.buildId).nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget-curiosity'