variables:
  projectBridge:  './Plotly.Bridge/Plotly.Bridge.csproj'
  projectH5:  './Plotly.H5/Plotly.H5.csproj'
  projectSharp:  './Plotly.Sharp/Plotly.Sharp.csproj'
  buildPlatform: 'AnyCPU'
  buildConfiguration: 'Release'

trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

steps:
- task: NuGetToolInstaller@0

- task: DotNetCoreCLI@2
  displayName: 'restore projectBridge'
  inputs:
    command: 'restore'
    projects: '$(projectBridge)'
    displayName: 'restore nuget'

- task: DotNetCoreCLI@2
  displayName: 'restore projectH5'
  inputs:
    command: 'restore'
    projects: '$(projectH5)'
    displayName: 'restore nuget'

- task: DotNetCoreCLI@2
  displayName: 'restore projectSharp'
  inputs:
    command: 'restore'
    projects: '$(projectSharp)'
    displayName: 'restore nuget'

- task: VSBuild@1
  displayName: 'build projectBridge'
  inputs:
    solution: '$(projectBridge)'
    msbuildArgs: '/t:pack /p:Version=0.0.$(build.buildId)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSBuild@1
  displayName: 'build projectBridge'
  inputs:
    solution: '$(projectH5)'
    msbuildArgs: '/t:pack /p:Version=0.0.$(build.buildId)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSBuild@1
  displayName: 'build projectSharp'
  inputs:
    solution: '$(projectSharp)'
    msbuildArgs: '/t:pack /p:Version=0.0.$(build.buildId)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CmdLine@2
  inputs:
    script: 'dir $(Build.SourcesDirectory)\*.nupkg /S'

- task: NuGetCommand@2
  displayName: 'push Plotly.Bridge to nuget'
  inputs:
    command: 'push'
    packagesToPush: '**/Plotly.Bridge.0.0.$(build.buildId).nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget-curiosity'

- task: NuGetCommand@2
  displayName: 'push Plotly.H5 to nuget'
  inputs:
    command: 'push'
    packagesToPush: '**/Plotly.H5.0.0.$(build.buildId).nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget-curiosity'


- task: NuGetCommand@2
  displayName: 'push Plotly.Sharp to nuget'
  inputs:
    command: 'push'
    packagesToPush: '**/Plotly.Sharp.0.0.$(build.buildId).nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget-curiosity'

