variables:
  projectPlotly:  './Transpose.Plotly/Transpose.Plotly.csproj'
  projectSharp:  './Plotly.Sharp/Plotly.Sharp.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: NuGetToolInstaller@1

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 9.x
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: PowerShell@2
  displayName: 'Set Version'
  inputs:
    targetType: 'inline'
    script: |
      $date=$(Get-Date -Format yyyy.M);
      Write-Host "##vso[task.setvariable variable=buildVersion]$date.$(build.buildId)"
    
- task: CmdLine@2
  inputs:
    script: 'dotnet tool update --global Transpose.Compiler'

- task: DotNetCoreCLI@2
  displayName: 'restore nuget'
  inputs:
    command: 'restore'
    projects: '$(projectPlotly)'

- task: DotNetCoreCLI@2
  displayName: 'build'
  inputs:
    command: 'build'
    projects: '$(projectPlotly)'
    arguments: '-c $(buildConfiguration) /p:Version=$(buildVersion) /p:AllowUnsafeBlocks=True /p:LangVersion=latest'

- task: DotNetCoreCLI@2
  displayName: 'pack nuget'
  inputs:
    command: 'pack'
    packagesToPack: '$(projectPlotly)'
    configuration: '$(buildConfiguration)'
    versioningScheme: 'off'
    buildProperties: 'Version="$(buildVersion)";AllowUnsafeBlocks="True";LangVersion="latest"'

- task: DotNetCoreCLI@2
  displayName: 'restore projectPlotly'
  inputs:
    command: 'restore'
    projects: '$(projectPlotly)'


- task: DotNetCoreCLI@2
  displayName: 'restore projectSharp'
  inputs:
    command: 'restore'
    projects: '$(projectSharp)'

- task: DotNetCoreCLI@2
  displayName: 'build projectPlotly'
  inputs:
    command: 'build'
    projects: '$(projectPlotly)'
    arguments: '-c $(buildConfiguration) /p:Version=$(buildVersion) /p:AssemblyVersion=$(buildVersion) /p:AllowUnsafeBlocks=True /p:WarningLevel=0 /p:AnalysisLevel=0'

# - task: DotNetCoreCLI@2
#   displayName: 'build projectSharp'
#   inputs:
#     command: 'build'
#     projects: '$(projectSharp)'
#     arguments: '-c $(buildConfiguration) /p:Version=$(buildVersion) /p:AssemblyVersion=$(buildVersion) /p:AllowUnsafeBlocks=True /p:WarningLevel=0 /p:AnalysisLevel=0'

- task: CmdLine@2
  inputs:
    script: 'dir $(Build.SourcesDirectory)\*.nupkg /S'

- task: NuGetCommand@2
  displayName: 'push Transpose.Plotly to nuget'
  inputs:
    command: 'push'
    packagesToPush: '**/Transpose.Plotly.$(buildVersion).nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget-curiosity'


# - task: NuGetCommand@2
#   displayName: 'push Plotly.Sharp to nuget'
#   inputs:
#     command: 'push'
#     packagesToPush: '**/Plotly.Sharp.$(buildVersion).nupkg'
#     nuGetFeedType: 'external'
#     publishFeedCredentials: 'nuget-curiosity-org'

